name: auto-generate-gitbook
on:
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install Nodejs
      uses: actions/setup-node@v1

    - name: configue gitbook
      run: |
        npm install -g gitbook-cli          
        gitbook install
        npm install -g gitbook-summary

    - name: Generate _book folder
      run: |
        book sm
        gitbook build
        cp SUMMARY.md _book

    - name: Deploy
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}
      run: |
        cd _book
        git config --global user.email "GitHub Actions"
        git config --global user.name "github-actions[bot]@users.noreply.github.com"
        git init
        git remote add origin https://${REF}
        git add .
        git commit -m "[Automation] Site update No.${GITHUB_RUN_NUMBER}"
        git branch -M main
        git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages
